### ISSUE TITLE
(use this as disscussion) should we deploy a github sites for this?

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/WikiMeower#1]

**Comment by CST1229** [comment]
YES

**Comment by wgyt** [comment]
the site is currently deployed to github pages at https://meower.org/WikiMeower/

**Comment by CloudGate1234** [comment]
> 

I believe that redirects to the wrong wiki. https://meower.miraheze.org/wiki/Main_Page is the correct one, but either way, I's already on the site. closing now.
