### ISSUE TITLE
switch to Mediawiki

### ISSUE THREAD

**Issue by CloudGate1234** [meower-media-co/WikiMeower#4]
this site is not a wiki. making it ourselves is unnecessary too much work for something that can be accomplished many times faster with mediawiki(or something similar).

**Comment by Bloctans** [comment]
well, DO YOU KNOW HOW TO MAKE A FULLY EDITABLE WIKI WITH AN ENTIRE STYLING FEATURE BUILT INTO IT?

**Comment by Mwalters75** [comment]
What he's saying is: It's "heavy" in size.

**Comment by CST1229** [comment]
> well, DO YOU KNOW HOW TO MAKE A FULLY EDITABLE WIKI WITH AN ENTIRE STYLING FEATURE BUILT INTO IT?

That's why they're suggesting using an already existing framework.

**Comment by CloudGate1234** [comment]
> > well, DO YOU KNOW HOW TO MAKE A FULLY EDITABLE WIKI WITH AN ENTIRE STYLING FEATURE BUILT INTO IT?
> 
> That's why they're suggesting using an already existing framework.

yes that is what I'm suggesting and it turn out someone just did this here: https://meower.miraheze.org/wiki/Main_Page

**Comment by Bloctans** [comment]
i mean, as long as it can support a custom topbar.

**Comment by Mwalters75** [comment]
Also, somehow, my Markdown got published here: [https://meower.miraheze.org/wiki/History](https://meower.miraheze.org/wiki/History). I made a account, and I'm editing it to make it look more look like the original.

**Comment by CloudGate1234** [comment]
> i mean, as long as it can support a custom topbar.

I believe it can. we should start to transfer to the new wiki and customize the topbar. I'll create new issue about transferring and close this one.
